### PR TITLE
2015-09-30-the-four-principles-of-contextual-inquiries.md

### PR DESCRIPTION
**Pull request by dherringatid**

### CODE REVIEW

**Comment by natoverse** [comment]
One edit then :shipit: - Jekyll will want the date in the filename like yyyy-mm-dd and you may need to put dashes in the filename where the spaces are, since that'll be part of what is generated for the URL on the page. Thanks!

**Comment by natoverse** [comment]
E.g., should be 2015-09-30-the-four-principles-of-contextual-inquiries.md

**Comment by dherringatid** [comment]
Hi Nathan, I updated the name.

**Comment by natoverse** [comment]
:+1: should be deployed live in a couple of minutes by Travis

**Comment by natoverse** [comment]
Oops, looks like the formatting was messed up. I'll take a look.

**Comment by dherringatid** [comment]
Thanks!

On Wed, Sep 30, 2015 at 4:50 PM Nathan Evans <notifications@github.com>
wrote:

> Oops, looks like the formatting was messed up. I'll take a look.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atsid/engineering/pull/27#issuecomment-144538987>.
>
-- 
*David Herring*
*Sr. User Experience Architect*
o: 571.270.7714  m: 703.608.1201
2051 Jamieson Avenue, Ste 502, Alexandria VA 22314
*david.herring@atsid.com <david.herring@atsid.com>*


ATS Inc. • www.atsid.com
D A T A   T O   D E C I S I O N S

Facebook <http://www.facebook.com/AppliedTechnicalSystems> | Twitter
<https://twitter.com/ats_inc> | LinkedIn
<http://www.linkedin.com/company/applied-technical-systems>

**Pull request merged**
