### PR TITLE
1 initial setup

### PR DESCRIPTION
**Pull request by natoverse**
- Added basic jekyll site
- Added github and opensource process files
- Basic editing of site to render the process file links on the home page
- gulp task to deploy to gh-pages

### CODE REVIEW

**Comment by darthtrevino** [comment]
:shipit:

**Comment by darthtrevino** [comment]
Out of curiosity, does the gulp-gh-pages push the distribution into a separate, live repo?

**Comment by natoverse** [comment]
No, it pushes it right to the gh-pages branch for this repo

**Comment by darthtrevino** [comment]
Oh weird - is a gh-pages branch idiomatic for what's live?

**Comment by natoverse** [comment]
We *could* go further and set it up the way you did with the main site, but I was thinking for the engineering content it would have fewer gates - get a PR approved, merge master, automatically deploy.

**Comment by natoverse** [comment]
Yes, gh-pages is the standard branch that GitHub will use to deploy as a GitHub Pages site automatically.

**Comment by darthtrevino** [comment]
:+1:

**Pull request merged**
